---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Login to Openshift
      command: "oc login --insecure-skip-tls-verify --token= --server="
      register: response

    - debug:
        msg: "{{ response.stdout_lines }}"

    - name: Show Projects
      command: "oc projects"
      register: response

    - debug:
        msg: "{{ response.stdout_lines }}"
