---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Show Projects
      command: "oc projects"
      register: response

    - debug:
        msg: "{{ response.stdout_lines }}"

    - name: Show Status
      command: "oc status"
      register: response

    - debug:
        msg: "{{ response.stdout_lines }}"
