---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Login to Openshift
      command: "oc login --token=eyJhbGciOiJSUzI1NiIsImtpZCI6Im5Jb3FUelg2Q24ya3pvS2poLVBlczNreFJFQ0xHSDFPS2lvUFZtbDBraTAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0b3dlci1jb250YWluZXItZ3JvdXAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiZGVmYXVsdC10b2tlbi1xNXhxdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMzU2NGY5ZjMtNjEyMS00NTM2LWI4ZjEtMDVjNWY5YjhhZDc2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRvd2VyLWNvbnRhaW5lci1ncm91cDpkZWZhdWx0In0.P8QwjbHH1wyzlWW9KkzckiMOeEJeE2mb3-FA7T7ZuLimpunkTtOwWtBS5wI9PkKH82h625WlfTlDFcBlanxYEw4L1DJ9YFx7GYoNwuAsxfhsgKYyFzDbt2ishC8TBg8orj34JPNBW4eiySE8Z3s6guNQEe99Byk4Zh3v5WZm_HJDEWLxTXex5LnktD0QVtrUhNIsEwwRuzseFcyCdahkXFk9Kv1PA-nk2YgaSXcIqC9SU9krM-rSo0WYVrBcC1WNZ_Lssc8zJOo2jnMPgZupgghyMdZZxoYs9PshNrGEWWYMCWoeL8OGaQsjYi8gwVvo4HUQ7IIK5cgb2u-98V-FWA --server=https://api.box.wul.fi:6443"
      register: response

    - debug:
        msg: "{{ response.stdout_lines }}"

    - name: Show Projects
      command: "oc projects"
      register: response

    - debug:
        msg: "{{ response.stdout_lines }}"
