---
- hosts: localhost
  gather_facts: false
  connection: local

  task:
    - name: Query information about all organizations associated to the user
      meraki_organization:
        auth_key: {{ auth_key }}
        state: query
      delegate_to: localhost