---
- name: Ping
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: ping
      command: "ping 172.30.37.184"
      register: response

    - debug:
        msg: "{{ response.stdout_lines }}"