---
- name: Ping
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: ping
      command: ping -c 4 google.com
      register: response

    - debug:
        msg: "{{ response.stdout_lines }}"
